mozilla/audioipc

server/src/lib.rs

Fix panic reported in gecko bug 1410107 but growing the slabs that hold client connections and streams.

Grow slabs as needed.

---

server/src/lib.rs

This should address BMO bug 1411849.

Drop any live ServerConns first when dropping Server.

---

server/src/lib.rs

Mainly this is to stop "ERROR:audioipc_server: server poll error:
Interrupted system call (os error 4)" appearing in unrelated Gecko test
logs.
https://bugzilla.mozilla.org/show_bug.cgi?id=1409904

Convert some error!s into warn!s.

---

server/src/lib.rs

See https://bugzilla.mozilla.org/show_bug.cgi?id=1409904#c8

server: Don't warn! on EINTR, just return to the caller.

---

audioipc/Cargo.toml
audioipc/src/codec.rs

This matches the version used by webrender, so it reduces the amount of code in the Firefox build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/32)

Update to bincode 0.9

---

client/Cargo.toml
client/src/context.rs
client/src/lib.rs
ipctest/src/client.rs

Change audioipc_client_init to take extra params.
Added `pool_size` (thread count) and `stack_size` params to `server_connection` as parameters to initialize AudioIPC client.
* pool_size: Controls the number of threads created in the pool.
* stack_size: Controls the size of the stack allocated per thread in the pool.
Because `audioipc_context_init` is a thin wrapper on `cubeb_context_init` style init, the extra params are passed via a thread local global variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/37)

Update cpupool version and add cpupool thread control.

---

client/src/context.rs
client/src/stream.rs

Also mark ClientContext and ClientStream #[repr(C)] to ensure the field layout matches what the libcubeb C ABI expects.
Before this, we were likely leaking the StreamCallbacks because cubeb_stream_user_ptr would return whatever value was in ClientStream.tokens... although I'm not sure why this wasn't crashing in Gecko.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/39)

client: Add user_ptr field to ClientStream for cubeb_stream_user_ptr.

---

client/src/stream.rs
ipctest/src/main.rs

Make ipctest fail if forked client process crashes.
Add debug assert that self.user_ptr() matches the user_ptr passed to stream_init.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/40)

Ipctest crash

---

client/src/stream.rs
ipctest/src/client.rs

This fixes issue #42.
I also had to bump the thread stack size in ipctest as it was failing to run on macOS, even before I made any changes to the code.  I've made it 64kB, but Gecko is actually using 256kB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/44)

Avoid passing the shm ptr for stream directions that weren't configured.

---

audioipc/src/codec.rs

Resolves https://bugzilla.mozilla.org/show_bug.cgi?id=1498244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/51)

Fixed a deprecation warning due to an API change in serializing integers

---

audioipc/src/messages.rs
client/src/stream.rs
server/src/server.rs

Rather than sizing the input and output buffer slices in bytes in the FFI wrapper and rewrapping the slice in data_callback based on the frame size, just create the buffer slice with the correct size in the FFI wrapper.
This also fixes a potential bug for input-only streams where we would pass the output frame size (0) and try to use it as the input frame size, causing input-only streams to fail to capture any data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/53)

Clean up reslicing of audio buffers in AudioIPC's server data callback.

---

audioipc/src/lib.rs
server/src/lib.rs

Fixes [BMO 1524818](https://bugzilla.mozilla.org/show_bug.cgi?id=1524818).
r? @chunminchang please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/54)

Silence error_chain deprecation warnings to fix build on nightly compiler.

---

audioipc/Cargo.toml
audioipc/build.rs
audioipc/src/cmsghdr.c
audioipc/src/fd_passing.rs

The static CMSG_BYTES assumes a particular layout for struct cmsghdr, but different platforms may have a different layout resulting in test failures.  Use some native C code to generate a platform-specific CMSG_BYTES equivalent for the tests.
r? @chunminchang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/55)

Fix cross-platform cmsghdr tests by generating valid cmsghdr in C.

---

client/src/context.rs

ClientContext::init would previously always succeed, even if later calls against the context would fail.  The addition of the ClientConnect message to ClientContext::init could cause an early error return without providing the caller with a valid context.
This is a simple fix for [BMO 1533539](https://bugzilla.mozilla.org/show_bug.cgi?id=1533539), suitable for uplifting to beta (67).  While investigating this I found several cleanups that I'd like to make to the error handling, but I'll leave them for a later bug to avoid complicating the beta (67) uplift patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/58)

Revert ClientContext::init error handling behaviour.

---

audioipc/build.rs
audioipc/src/cmsg.rs
audioipc/src/messagestream_win.rs

- Issue #56: Avoid warning when building with rustc >= 1.34.
- Issue #57: Don't build cmsghdr.c test on non-Unix.
- [BMO #1536613](https://bugzilla.mozilla.org/show_bug.cgi?id=1536613): Fix build failure on 32-bit MUSL targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/59)

Fixes for #56, #57, and BMO #1536613

---

audioipc/src/fd_passing.rs

Newer versions of Rust complain about this by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/61)

remove unnecessary `mut`

---

ipctest/src/main.rs
server/src/lib.rs
server/src/server.rs

This is needed for BMO #14886666.

Extend audioipc_server_start to accept a context name to be passed to cubeb_init.

---

server/src/server.rs

Swallowing errors (by converting them to panics via `expect`) in CubebDeviceCollectionManager::internal_register is a bad idea: registration can fail for legitimate reasons plus we need to report CUBEB_ERROR_NOT_SUPPORTED correctly for unimplemented backends.
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1569460

server: Don't swallow errors in register_device_collection_changed.

---

audioipc/src/messages.rs
client/Cargo.toml
client/src/context.rs
client/src/lib.rs
server/src/server.rs

With `audio_thread_priority` version `0.20` it's possible to promote a
thread to real-time from another process. This allows removing the
workaround that was previously done to create the threads early before
the sandbox lockdown.
Additionaly, this patch adds a new message that allows passing a
`RtPriorityThreadInfo` struct via IPC, so that the server can promote
a client thread in a sandboxed process.
This is part of [BMO#1575883](https://bugzilla.mozilla.org/show_bug.cgi?id=1575883).

Remove the code to start the audio callback threads early, and add a message to promote a thread to RT from the server process.

---

audioipc/Cargo.toml
client/Cargo.toml
server/Cargo.toml

0.20.2 just got published with a fix for musl.

Gecko re-sync: use the right `audio_thread_priority` version

---

audioipc/Cargo.toml
client/Cargo.toml
server/Cargo.toml

This fixes https://github.com/djg/audioipc-2/issues/80.

Use audio_thread_priority version 0.21 to fix a compilation issue on Linux when using musl

---

audioipc/Cargo.toml
audioipc/src/lib.rs
audioipc/src/messagestream_unix.rs
audioipc/src/messagestream_win.rs
audioipc/src/rpc/client/mod.rs
audioipc/src/rpc/server.rs
audioipc/src/tokio_named_pipes.rs
server/src/lib.rs
server/src/server.rs

This is the same changes included in BMO 1590249:
- Fix tokio_named_pipes::NamedPipe shutdown
- Shutdown ClientHandler and ServerHandler correctly on drop
- Clarify server/client pipe ends and use appropriate end in appropriate location

Windows pipe fixes

---

audioipc/src/core.rs
client/src/context.rs
client/src/lib.rs
ipctest/src/client.rs
server/src/lib.rs

`thread_create_callback` is used to register AudioIPC threads with Gecko's profiler.  Per [BMO 1614547](https://bugzilla.mozilla.org/show_bug.cgi?id=1614547) and related bugs, we also need to ensure threads unregister when destroyed.  This adds `thread_destroy_callback` and arranges for it to be called in the appropriate places.

audioipc: Add thread_destroy_callback for unregistering profiler.

---

audioipc/src/lib.rs
audioipc/src/shm.rs
server/src/server.rs

The existing code attempts to preallocate the shm area with
File::set_len, but that approach doesn't work on filesystems that
allow sparse files.  Accessing a mapped page in a shm area where the
backing file is lazily allocated can fault with SIGBUS (on Unix-like
platforms) due to low disk space.  To avoid this difficult to handle
failure mode, preallocate the entire shm area using OS-specific
techniques before mapping.
This change also also reworks the shm API slightly to take a path
fragment rather than a complete path.  This allows the shm code to try
creating the shm via preferential paths (e.g. /dev/shm on Linux)
before falling back to safe defaults.

audioipc: Preallocate shm area before mapping to avoid late faults.

---

server/src/server.rs

The existing code had the lifetime of a cubeb_devid slightly wrong.  It
doesn't start and stop at each enumerate, it belongs to a fixed set of
possible cubeb_devids tied to the lifetime of the cubeb context.
enumerate presents a (possibly incomplete, due to device removal) view of
that set.
- Remove DevIdMap::reset
- DevIdMap::to_handle checks for existing mapping before inserting

server: Don't reset DevIdMap on enumerate.

---

audioipc/src/shm.rs

The `std::ffi::CString::new(id).unwrap()` will create a temporary
variable. `std::ffi::CString::new(id).unwrap().as_ptr()` is a pointer
pointing to a temporary variable. Using this pointer directly is unsafe
since we cannot make sure the variable is alive when the pointer is
referred. It's better to save the variable returned from `CString::new()`
and use its pointer (in the same scope of the variable) when we need.
Run `cargo clippy` with `CString::new(text).unwrap().as_ptr()` will 
lead to a `temporary_cstring_as_ptr` error. Here is a [playground test](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a45431ff7366612aa266b69cfbd3d308).
r? @kinetiknz

Avoid using the pointer of a temporary variable

---

client/src/stream.rs

This could fail due to low available address space (for example), so unwrapping the Result is inappropriate.
This is intended to be a fix for [BMO 1621360](https://bugzilla.mozilla.org/show_bug.cgi?id=1621360).

client: Handle shmem setup error gracefully.

---

server/src/lib.rs
server/src/server.rs

Re-attempt `cubeb_init` when a new client attaches, if the last initialization failed.
Addresses [BMO 1636722](https://bugzilla.mozilla.org/show_bug.cgi?id=1636722).

server: Re-init libcubeb rather than caching failure.

---

audioipc/src/handle_passing.rs
ipctest/src/main.rs

Unlike the pseudo-handle returned by [`GetCurrentProcess`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocess#remarks), the handle returned by [`OpenProcess`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess#remarks) must be closed after use.
Addresses [BMO 1644522](https://bugzilla.mozilla.org/show_bug.cgi?id=1644522).

audioipc: Close process handle after use.

---

audioipc/src/fd_passing.rs
audioipc/src/frame.rs
audioipc/src/handle_passing.rs
audioipc/src/messages.rs
client/src/stream.rs
server/src/server.rs

Split StreamCreate into StreamCreate and StreamInit.  StreamCreate performs
the pre-libcubeb IPC setup and StreamInit completes the libcubeb stream
initialization.  This avoids a circular dependency where a server-side
StreamInit needed to send messages back to the client before the client
could progress far enough to receive and process them.
Fix for [BMO 1661398](https://bugzilla.mozilla.org/show_bug.cgi?id=1661398).

Split stream initialization into two phases.

---

server/src/server.rs

If `stream_init` fails, there is a partially initialized `ServerStream` left behind in the `CubebServer`'s stream slab.  Since this will never be used again, we need to remove it explicitly rather than relying on a `stream_destroy`.
Follow up to e925e82ca9887af9b04d92a5e304b5df94942c79.  I had noted this with a comment, but forgot to fix it before finishing e925e82ca9887af9b04d92a5e304b5df94942c79.

server: Clean up ServerStream if stream_init fails.

---

audioipc/Cargo.toml
audioipc/src/shm.rs

Add support for Android's [ASharedMemory](https://developer.android.com/ndk/reference/group/memory) to shm.rs.

audioipc: Add support for ashmem to shm.rs.

---

audioipc/Cargo.toml
audioipc/src/shm.rs

The crate [memmap](https://crates.io/crates/memmap) has been marked unmaintained, see the [advisory](https://rustsec.org/advisories/RUSTSEC-2020-0077).
This PR replaces the dependency with [memmap2](https://crates.io/crates/memmap2), which is a maintained fork of memmap.

Replace dependency to memmap with memmap2

---

audioipc/Cargo.toml
audioipc/src/codec.rs

This was attempted in https://github.com/mozilla/audioipc-2/commit/b0f2a7a9325a8866be13875260df2dceb1de2388, but reverted due to both local breakage and issues landing bincode 1.3 in Gecko ([BMO 1675534](https://bugzilla.mozilla.org/show_bug.cgi?id=1675534)).
For backwards compat reasons, bincode's standalone `serialize`, `deserialize`, and `serialized_size` functions use a different set of options to the default returned by `bincode::options`.  codec.rs used the bare `deserialize` but called `serialize` via `bincode::options`, resulting in an incompatible serialization between encode and decode.
Leaving this PR as a draft, since may still be other issues blocking bincode 1.3 in Gecko.

audioipc: Update to bincode 1.3 again.

---

server/src/server.rs

If the client abruptly disconnects (e.g. crashed) between the first and second phase of stream init, waiting for the `shm_setup` response on the server can result in an error.  Handle this gracefully rather than unwrapping the response.
Addresses [BMO #1725749](https://bugzilla.mozilla.org/show_bug.cgi?id=1725749).

server: Handle client error during stream_init shmem setup.

---

ipctest/src/main.rs
server/src/lib.rs
server/src/server.rs

The shm_area_size parameter to audioipc_server_new_client now serves as a hard override to force a specific shm area size.  The default value of 0 allows the server to estimate an appropriate size for each stream.  For common streams, this reduces the shm overhead from ~2MB to ~192kB.
This is a short term improvement until issue 124 is addressed.  With issue 124 addressed, it should be possible to reduce shm overhead to ~20-64kB.

server: Estimate shm_area_size based on stream config.

---

client/src/lib.rs
ipctest/src/main.rs
server/src/lib.rs

This will be used by Gecko to link AudioIPC server threads to the Firefox Profiler as discussed in [BMO 1728023](https://bugzilla.mozilla.org/show_bug.cgi?id=1728023).

server: Register server threads via supplied callback.

---

audioipc/Cargo.toml

ashmem 0.1 is yanked on crates.io making `cargo audit` warn against it.
It doesn't seem there is much difference between the pinned git version here and the latest version on the crates.io: https://github.com/kinetiknz/ashmem-rs/commits/master and I believe it's normally preferable if we can use the crate from crates.io rather than pin a git revision.

Use ashmem crate from crates.io

---

client/Cargo.toml
client/src/stream.rs

Per [BMO 1744102](https://bugzilla.mozilla.org/show_bug.cgi?id=1744102), there's a desire to switch to Rust's built-in fallible allocations now that they're stable in 1.57.

Drop `fallible_collections` and switch to Rust 1.57 fallible allocations.

---

README.md
audioipc/src/codec.rs
audioipc/src/ipccore.rs
audioipc/src/messages.rs
audioipc/src/rpccore.rs
ipctest/src/client.rs
server/src/lib.rs
server/src/server.rs

Various fixes found while stress testing PR #130 integrated with Gecko on various platforms.
- 25ba70ed054c30dc3e83c98614ebba316ef491ad: Consume incoming cmsg buffer correctly.
- `clone` was causing processed handles to be left in the cmsg buffer, which were then ignored when trying to associate them with the incoming message in `set_owned_handle`.
- cc170ab91be6659ae8e1715185f327db01fedcfd: Notify EventLoop when proxy dropped, and clean up broken connections when handling wakes.
- Resulted in a shutdown hang in the AudioIPC client while waiting for the server's CallbackClient to be removed.
- 06b8727b8e771cdeba49934066a12481773ddcf2: ipctest: 64kB stack is too small for Client Callback thread on Windows.
- ipctest was using an unusually small stack size, resulting in an intermittent …

Various fixes for "Core IPC messaging rewrite" (PR #130)

---

audioipc/src/ipccore.rs
audioipc/src/rpccore.rs
server/src/lib.rs

The fix in 50ae2a6 was incomplete, it left a potential race where the EventLoopThread associated with the Proxy would handle the wake before the Sender was dropped.  This resulted in the EventLoopThread failing to clean up a disconnected Proxy, since the last attempt to read from the Receiver the Proxy is attached to would succeed rather than fail as expected.
Follow up to https://github.com/mozilla/audioipc-2/pull/134.

Fix potential "lost" wake when dropping Proxy

---

audioipc/src/ipccore.rs
audioipc/src/messages.rs
audioipc/src/sys/unix/cmsg.rs
audioipc/src/sys/unix/mod.rs

This fixes an issue where the Driver would attempt to decode and associate a handle to a message that didn't expect a handle when multiple messages were present in the inbound decode buffer, triggering the assert added in https://github.com/mozilla/audioipc-2/commit/25ba70ed054c30dc3e83c98614ebba316ef491ad via PR #134.  The tests I'm adding in issue #135 will cover this case as part of the tests for the original https://github.com/mozilla/audioipc-2/commit/25ba70ed054c30dc3e83c98614ebba316ef491ad fix.
- Move cmsg handling into standalone {encode,decode}_handle functions.
- Rename AssocRawPlatformHandle to AssociateHandleForMessage
- Roll take_handle_for_send and set_remote_handle_value into
prepare_send_message_handle, allowing more of the caller logic to be shared
between OS platforms …

Improve handle {de,}serialization logic.

---

audioipc/Cargo.toml
audioipc/src/shm.rs

Also bump ashmem to 0.1.2, which contains minor fixes for Android.
Without an explicit length set on `MmapOptions`, [`mmap_mut`](https://github.com/RazrFalcon/memmap2-rs/blob/master/src/lib.rs#L398) tries to query the [file length](https://github.com/RazrFalcon/memmap2-rs/blob/master/src/lib.rs#L240), which results in an attempt to call [`fstat`](https://github.com/RazrFalcon/memmap2-rs/blob/master/src/unix.rs#L278).  This fails on file descriptors supplied by Android's ashmem, causing shared memory setup to fail.
Since we already know the expected size of the mapping we can set the length explicitly and avoid the `fstat`.
This also solves [bug 1747932](https://bugzilla.mozilla.org/show_bug.cgi?id=1747932) for macOS 10.13, where the `fstat` is blocked by the content sandbox.

audioipc: Specify explicit length when configuring MmapMut on both sides of remote.

---

audioipc/src/codec.rs
audioipc/src/lib.rs

This prefix check shouldn't be necessary in a working system, but it may
help debug [BMO 1751318](https://bugzilla.mozilla.org/show_bug.cgi?id=1751318).

audioipc: Prefix each IPC message with a magic value, verified on decode.

---

audioipc/src/rpccore.rs
server/src/server.rs

The threads that cubeb executes the data, state, and device_change
callbacks on is undefined. Using a single rpc Proxy for all three of the
ServerStreamCallbacks callbacks can result in the Proxy being used from
multiple threads concurrently (e.g. data_callback on the OS audio
thread and state_callback on the Server RPC thread) depending on the
cubeb backend in use.
Also remove the mpsc::channel clone from make_client, since it was
obscuring the root cause of this issue.

Use separate rpc Proxy clones for each of ServerStreamCallbacks's callbacks.

---

audioipc/src/messages.rs
audioipc/src/shm.rs
client/src/stream.rs
server/src/server.rs

By slightly reordering the initialization steps in
StreamCreate/StreamInit, it's possible to pass both the SharedMem handle
and callback RPC pipe via client RPC during stream creation.  This
avoids the client callback thread having to handle the SharedMem
messages as part of the initialization sequence.
The second commit cleans up some code in CallbackServer::process left over
from AudioIPC v1 requirements.

Simplify stream SharedMem configuration between server/client.

---

audioipc/Cargo.toml
audioipc/src/ipccore.rs
audioipc/src/messages.rs
audioipc/src/sys/unix/cmsg.rs
audioipc/src/sys/unix/mod.rs

This isn't the most elegant fix, but it's a fiddly issue.  I may revisit this again later if I think of a cleaner way to handle it.
On some 64-bit platforms, due to struct alignment requirements, the smallest `cmsghdr` has capacity for 2 fds even if only 1 is expected/requested.  Due to buffer coalescing, multiple `sendmsg` calls may arrive via a single `recvmsg`, resulting in a situation where the `cmsghdr` contains multiple (maximum 2) fds.
This addresses [BMO 1750345](https://bugzilla.mozilla.org/show_bug.cgi?id=1750345).

Handle up to 2 fds per decoded `cmsghdr` buffer.

---

audioipc/Cargo.toml
client/Cargo.toml
client/src/send_recv.rs
ipctest/Cargo.toml
server/Cargo.toml

This uses the "winapi" feature flag to continue building against
"winapi" rather than using "windows-rs".
See https://github.com/padenot/audio_thread_priority/pull/13

Update macos branch to audio_thread_priority 0.26.0 and cubeb-rs 0.10.

---

audioipc/Cargo.toml
audioipc/src/lib.rs
audioipc/src/tokio_uds_stream.rs
client/Cargo.toml
client/src/send_recv.rs
ipctest/Cargo.toml
server/Cargo.toml

This uses the "winapi" feature flag to continue building against
"winapi" rather than using "windows-rs".
See https://github.com/padenot/audio_thread_priority/pull/13
Also includes two small fixes for CI failures.

Update tokio branch to audio_thread_priority 0.26.0 and cubeb-rs 0.10.

---

audioipc/src/shm.rs
server/src/server.rs

Rather than hit an unwrap accessing the shm slice, validate the input/output slice length against the shm's maximum size and log/return error if invalid.

server: Validity check input/output against shm limit.

---

audioipc/Cargo.toml
audioipc/src/ipccore.rs
audioipc/src/rpccore.rs
client/src/context.rs
client/src/send_recv.rs
server/src/server.rs

Avoid several heap allocations by converting Proxy::call to blocking.  We cache a single channel on each Proxy rather than creating a new one per call.  crossbeam's bounded channels perform any required heap allocations when first initialized, further avoiding allocations on each channel send/recv with the std mpsc channel.

Reduce per-call RPC overhead

---

audioipc/src/ipccore.rs
server/src/server.rs

Since CubebDeviceCollectionManager tracks each callback registration independently, trying to unregister for "all" when CubebServer drops would fail to match and made CubebServer's drop handling effectively a no-op.
Also downgrade some EventLoop warnings to debug messages.

server: Unregister input and output device collection change callbacks separately

---

audioipc/src/ipccore.rs
audioipc/src/rpccore.rs
client/src/context.rs
client/src/stream.rs
server/src/server.rs

Make rpccore::Proxy's ProxyManager reference Arc instead of Weak, use a flag on the ProxyManager to signal disconnection between the ClientHandler and any Proxies.
Also add test for cloning RPC Proxy after the ClientHandler has dropped.
This is intended to address [BMO 1788544](https://bugzilla.mozilla.org/show_bug.cgi?id=1788544).

Improve Proxy<->ClientHandler disconnection handling.

---

server/src/server.rs

With some Cubeb backends (e.g. PulseAudio), a state callback indicating a stream error may be triggered synchronously during stream initialization when opening a device that is no longer present.  The client side is not able to receive these callbacks during initialization, so log and ignore them. The stream initialization will fail normally and initiate any required cleanup.
This should address [BMO 1801049](https://bugzilla.mozilla.org/show_bug.cgi?id=1801049).

server: Log and ignore stream callbacks received before stream initialization completes

---

audioipc/src/codec.rs
client/src/context.rs
server/src/lib.rs
server/src/server.rs

Matthew, this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1814692#c10.
This is reverting back to the previous value (in the other branch). `256 / 48000` is quite small, it's about 5ms.
For real-time scenario (= `MediaTrackGraph`), we're using buffer sizes of 10ms on Windows, about 10ms on macOS (in WebRTC calls, it's smaller when just doing Web Audio), but often a lot larger on Linux desktop and Android.
So on Linux desktop, this means that we're only allowing a fraction of the possible real-time budget (which is plenty for normal playback, not so much for demanding Web Audio API scenarios, especially when using big buffers with PulseAudio, it's nicer when using pipewire).
Additionally, WebRTC uses `SCHED_FIFO` for desktop capture, and that's converting/copying …

Use a larger default RLIMIT_RTTIME for now

---

audioipc/Cargo.toml
audioipc/src/ipccore.rs
audioipc/src/rpccore.rs
client/src/context.rs
client/src/stream.rs
server/src/server.rs

Rust/crossbeam channels turn out not to be ideal for RT-safe uses, since they may allocate and call `thread::yield_now()`.  Instead, use a `Completion` object allocated on the stack to wait for the response from the handler thread.

Switch to `Completion` and thread-safe queue instead of using channels.

---

audioipc/src/ipccore.rs
audioipc/src/rpccore.rs

This centralises the handling of Weak->Arc upgrades when sending, and avoids a footgun where the sender could keep the RequestQueue alive while waiting for a request to complete.
The existing code made this exact mistake: upgrading Weak->Arc, sending a request, and then waiting on the response while the upgraded Arc remained in scope.  The sender must drop the Arc after queuing the request and before waiting on the response to avoid the situation where the request is successfully queued while the server is shutting down - resulting in the queued Requests never being dropped and the sender becoming deadlocked.

Refactor shared ArrayQueue logic into RequestQueue wrapper.

---

audioipc/src/ipccore.rs

In `EventLoop::poll`, remove the `!done` assert and just return the result of `handle_wake`.  `Connection::handle_wake` may return `Ok(true)` if sending fails due to the remote having disconnected, in which case we'll remove the connection during `done` handling later.
In `Connection::recv_inbound`, remove the two `self.inbound.is_empty()` asserts - since the connection is in error, it will be removed when `recv_inbound` returns `Ok(true)` or an error, so we don't care about (and couldn't react to) the contents of the inbound buffer.

Remove unnecessary asserts

---

.github/workflows/build.yml
audioipc/Cargo.toml
audioipc/src/lib.rs
audioipc/src/shm.rs
audioipc/src/sys/unix/cmsg.rs
audioipc/src/sys/windows/mod.rs
client/Cargo.toml
client/src/context.rs
ipctest/Cargo.toml
ipctest/src/main.rs
server/Cargo.toml

[Now that windows-sys can be imported to Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1853084), switch AudioIPC from winapi to windows-sys.  Required changes are largely mechanical, but `HANDLE` changes from a `* c_void` to an `isize`, so casts have changed in a couple of places.

Switch to windows-sys.

---

audioipc/Cargo.toml
audioipc/src/ipccore.rs
audioipc/src/messages.rs
client/Cargo.toml
client/src/context.rs
client/src/lib.rs
client/src/stream.rs
ipctest/Cargo.toml
server/Cargo.toml
server/src/server.rs

Besides the ABI change adaptations, this PR also temporarily moves windows-sys back to 0.48 and re-bumps it, such that there is a rev that can easily be merged into gecko (which doesn't have windows-sys 0.52 yet); and fixes some warnings with the latest nightly toolchain in order to green up CI.

Bump cubeb to 0.12 and handle ABI changes

---

server/src/server.rs

The client side does not allow CallbackData::Req of size zero. This handles it on the server side by returning early.
The background for this is https://bugzilla.mozilla.org/show_bug.cgi?id=1907367 where something is causing data callbacks of size zero and tripping an assertion, but we have not reproduced and an audit is not conclusive as to where the root cause is.

Handle data callbacks of size zero
