audioipc/src/msg.rs

This is probably the cause of the "socket write" failures that we have seen reported in https://bugzil.la/1410702

audioipc: Handle EINTR from recvmsg/sendmsg calls.

---

server/src/lib.rs

state_callback() and data_callback() can be called from multiple
threads.  To protect the send/receive pair of calls, a Mutex is added
to Connection to prevent one thread from starving when two threads try
to wait on the socket in recvmsg.
(From bugzil.la/1414623)

Connect callback send/receive with Mutex.

---

server/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/25)

server: Wait for Quit response in ServerWrapper::shutdown.

---

audioipc/Cargo.toml
audioipc/src/messages.rs
ipctest/Cargo.toml
server/Cargo.toml

Update stream params to handle new prefs member. Bump versions as prefs member has been added. Could this please be tested? I'm having issues with local building in a VM (This is Linux only ATM, yes?), but will continue to try get it working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/29)

Add stream params preferences member for compat with cubeb. Bump versions.

---

client/Cargo.toml
client/src/context.rs
client/src/stream.rs
server/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/30)

Address issue #28

---

server/Cargo.toml
server/src/lib.rs

Results weren't being handled correctly.  Errors were being reported as success.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/33)

Fix error handling

---

ipctest/src/client.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/49)

Fix compile error in ipctest

---

audioipc/build.rs
audioipc/src/cmsg.rs
audioipc/src/messagestream_win.rs
client/src/context.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/60)

Bmo1533539

---

audioipc/Cargo.toml
audioipc/src/fd_passing.rs
audioipc/src/lib.rs
audioipc/src/messages.rs
client/Cargo.toml
client/src/context.rs
client/src/stream.rs
ipctest/Cargo.toml
ipctest/src/client.rs
server/Cargo.toml
server/src/server.rs

This fixes issue #50.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/djg/audioipc-2/62)

Implement remoting for remaining unimplemented API 

---

ipctest/src/main.rs
server/Cargo.toml
server/src/lib.rs
server/src/server.rs

This is needed for BMO #1439925.

Support libcubeb backend selection via new parameter to audioipc_server_start()

---

server/src/server.rs

The previous implementation of cubeb_register_device_collection_changed in https://github.com/djg/audioipc-2/pull/62 applied the registration directly to the cubeb context.  CubebServer logically represents a cubeb context, but the underlying cubeb context is actually shared (via TLS) to multiple CubebServers (with one CubebServer per attached client).
The fix requires introducing a layer to manage device collection changed callbacks for multiple CubebServers using a single cubeb context.  This PR introduces a CubebDeviceCollectionManager that rides along with the shared TLS cubeb context and maps multiple CubebServer registrations to the shared cubeb context.

Add CubebDeviceCollectionManager to handle mapping between CubebServer and shared cubeb context.

---

audioipc/Cargo.toml
audioipc/src/messages.rs
client/Cargo.toml
client/src/stream.rs
ipctest/Cargo.toml
server/Cargo.toml
server/src/server.rs

Part of https://github.com/kinetiknz/cubeb/pull/532

Update to cubeb-rs 0.6.0; remove panning API.

---

audioipc/Cargo.toml
audioipc/src/frame.rs
audioipc/src/handle_passing.rs
audioipc/src/lib.rs
audioipc/src/messagestream_win.rs
client/src/context.rs
client/src/lib.rs
client/src/stream.rs
server/src/server.rs

Various minor fixes

---

audioipc/src/codec.rs
audioipc/src/lib.rs
audioipc/src/messages.rs
audioipc/src/messagestream_win.rs
client/src/context.rs
client/src/lib.rs
client/src/stream.rs
server/Cargo.toml
server/src/lib.rs
server/src/server.rs

More minor fixes

---

audioipc/src/cmsg.rs

- Replace our versions of CMSG_SPACE and CMSG_LEN with libc implementations.
- Avoid depending on our version of CMSG_ALIGN, since it's non-portable.
- Avoid need for align_buf, since we always leave the buffer correctly aligned now.
Tested on x86_64: Linux, FreeBSD, OpenBSD, macOS.
This fixes issue #83.

Rework cmsg.rs internals to address portability issues.

---

audioipc/src/lib.rs
audioipc/src/messages.rs
audioipc/src/rpc/client/mod.rs
audioipc/src/rpc/server.rs
client/src/context.rs
client/src/stream.rs
server/src/lib.rs

This fixes BMO 1607802, see https://bugzilla.mozilla.org/show_bug.cgi?id=1607802#c4 for bug analysis.

Don't leak IPC connections in error/shutdown path

---

ipctest/src/main.rs

Observed on macOS: sometimes during startup, ipctest would hang after
printing the startup banner.
It turns out that the ipctest child could hang waiting for a lock deep
inside tokio; however the lock had been taken (and dropped) in the
parent during initialization.  fork() would just happen to clone the
process at a bad time, leaving tokio's internal state unusable in the
child.
To avoid this entire class of problem, ipctest on Unix now uses a
similar technique to Windows to bootstrap - after the client fd is
allocated, ipctest forks and then execs to reset its process state
before continuing with the audioipc tests.

ipctest: Fix random hang during startup.

---

server/src/server.rs

Add debug logging to gather data about BMO 1594216 and 1612044

---

server/src/server.rs

server: Map cubeb_devids to IPC-portable handles.

---

audioipc/src/cmsg.rs
audioipc/src/messagestream_win.rs
audioipc/src/tokio_named_pipes.rs
client/src/context.rs
client/src/stream.rs
ipctest/src/main.rs
server/src/lib.rs
server/src/server.rs

Done with:
```
rustfmt $(fd \.rs$)
```
with rustfmt 1.4.11-stable (1838235 2019-12-03)

Rustfmt the code

---

audioipc/src/shm.rs

[`memfd`](http://man7.org/linux/man-pages/man2/memfd_create.2.html), available in recent Linux kernels, provides a way to create anonymous shared memory mappings referenced by an fd.  This avoids needing to preallocate and then unlink files in the filesystem to acquire an fd.

audioipc: Try memfd before /dev/shm in open_shm_file.

---

server/src/server.rs

Return the correct message when getting input latency

---

audioipc/Cargo.toml
client/Cargo.toml
server/Cargo.toml

This is just a build fix for android x86.

audio_thread_priority 0.23.4

---

audioipc/Cargo.toml
audioipc/src/messages.rs
client/Cargo.toml
client/src/stream.rs
ipctest/Cargo.toml
server/Cargo.toml
server/src/server.rs

Related to kinetiknz/cubeb#615

Implement remoting for cubeb_stream_set_name.

---

server/src/server.rs

server: Fix potential race in CubebDeviceCollectionManager.

---

client/src/stream.rs

Synchronize ClientStream drop on CallbackServer channel drop.  This ties the lifetime of the CallbackServer directly to the ClientStream, closing a small window during drop where CallbackServer could race and continue executing cubeb user callbacks.

client: wait for CallbackServer to drop before finishing ClientStream drop.

---

audioipc/Cargo.toml
audioipc/src/messages.rs
client/Cargo.toml
client/src/stream.rs
ipctest/Cargo.toml
server/Cargo.toml
server/src/server.rs

Remove cubeb_stream_reset_default_device API.

---

server/src/server.rs

This avoids keeping unused `SharedMem` alive in the AudioIPC server for unused stream directions.

server: Drop unused SharedMem after RPC setup.

---

audioipc/src/shm.rs

Try creating a shared memory segment via [`shm_open`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/shm_open.2.html) before falling back to a temporary file.  This is a better approach for macOS and other systems lacking memfd.
[`shm_unlink`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/shm_unlink.2.html) is called immediately after a successful `shm_open` to minimize the lifetime of the shared memory segment `name`; the underlying shared memory segment is kept alive by the fd returned by `shm_open` and the fd we later clone to the client to use in `SharedMem::from`.

audioipc: Try `shm_open` before falling back to temp file.

---

audioipc/src/ipccore.rs

This fixes continuous spurious writable events for NamedPipes on Windows, and avoids a few unnecessary syscalls on other platforms.
On Windows, [reregistering](https://github.com/tokio-rs/mio/blob/d400ddfc97212b4a2844d741b095dab2c6d15543/src/sys/windows/named_pipe.rs#L426) hits [this case](https://github.com/tokio-rs/mio/blob/d400ddfc97212b4a2844d741b095dab2c6d15543/src/sys/windows/named_pipe.rs#L589), causing every reregister to generate a writable event.

Only update readiness registration on Connection if it changed.

---

audioipc/src/ipccore.rs

Allow errors to bubble to the caller rather than calling `expect` and panicking.
This addresses the failure mentioned in [BMO 1726279 comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1726279#c8).

Return error instead of panicking when add_connection called on shutdown server.

---

audioipc/src/ipccore.rs

This addresses [BMO 1750477](https://bugzilla.mozilla.org/show_bug.cgi?id=1750477).

ipccore: Handle interrupted Poll::poll() in EventLoop:poll().

---

server/src/server.rs

If a CubebServer is ever dropped as a result of an error (e.g. client abruptly disconnects), any live device collection callbacks registered for that server must be removed.

server: Clean up device_collection_change_callbacks registration on Drop.

---

audioipc/Cargo.toml
client/src/context.rs
ipctest/Cargo.toml
server/Cargo.toml

Fix some clippy warnings so we can run the tests in PRs

Fix clippy warnings

---

server/src/server.rs

Rather than including a `devtype` on the `DeviceCollectionChangeCallbacks` and using it inside `CubebDeviceCollectionMananger` to maintain a unique list of callbacks, use a pair of `(DeviceCollectionChangeCallbacks, DeviceType)` for each register/unregister call, making the overall implementation of `CubebDeviceCollectionManager` much simpler.
Now that CubebDeviceCollectionManager no longer needs to mutate DeviceCollectionChangeCallbacks, it's possible to drop the `RefCell` wrapping it.

server: Simplify `CubebDeviceCollectionManager`.

---

client/src/stream.rs

We already handle this in the original audioipc branch, but it was missed in a refactoring for the macos branch.  Verified with existing cubeb GTests.

client: Pass ptr::null() to data_cb when buffer is unused for stream type.

---

audioipc/Cargo.toml
client/Cargo.toml
server/Cargo.toml

This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1861812

Revert removal of `default-features = false` for audio_thread_priority.
